### ISSUE TITLE
Use custom upstream DoH server

### ISSUE THREAD

**Issue by andrewkdinh** [qdm12/dns#12]
Are there any plans to add support for custom upstream DoH servers? For example, I would like to use [NextDNS](https://nextdns.io/) DoH servers.

**Comment by qdm12** [comment]
Unbound does not support DoH and I'm not aware of a DNS forwarder server, but I'll search about it. Let me know if you know any that can act as a standard DNS server (on UDP 53) and forward requests over HTTPS.

I might also code one eventually one day.

**Comment by qdm12** [comment]
Hello, I am still writing some Go program to supervise the processes and the set up the config. I might add a DNS over HTTPs option, written in Go, in the future (probably a few months though, pretty busy these days). You can join the new Slack channel to discuss about it / keep updated: [here](https://join.slack.com/t/qdm12/shared_invite/enQtODMwMDQyMTAxMjY1LTU1YjE1MTVhNTBmNTViNzJiZmQwZWRmMDhhZjEyNjVhZGM4YmIxOTMxOTYzN2U0N2U2YjQ2MDk3YmYxN2NiNTc)

**Comment by qdm12** [comment]
Closing in favor of #51
