### ISSUE TITLE
Cannot start v2-beta container: invalid value for max entries of the LRU cache

### ISSUE THREAD

**Issue by Arderos** [qdm12/dns#126]
I'm trying to start the latest v2.0.0-beta container and it fails with:
`ERROR reading environment variables: cache settings: LRU max entries: invalid value for max entries of the LRU cache: cannot be zero`
The ENV variables are not set explicitly so should be by default - lru and 10000, which I can confirm by doing docker inspect:
```
> sudo docker inspect dns | grep CACHE
                "CACHE_TYPE=lru",
                "CACHE_LRU_MAX_ENTRIES=10000",
```
I tried to set them explicitly to no avail

**Comment by qdm12** [comment]
Are you sure? What version are you running? Maybe repull the image?
Running `docker run -it --rm qmcgaw/dns:v2.0.0-beta` works for me without issue 🤔

**Comment by Arderos** [comment]
> Are you sure? What version are you running? Maybe repull the image? Running `docker run -it --rm qmcgaw/dns:v2.0.0-beta` works for me without issue 🤔

This is really quite strange. Complete recreation of the container helped. Thanks! :)
