### ISSUE TITLE
feature request: expose metrics

### ISSUE THREAD

**Issue by Kampe** [qdm12/dns#41]
Hey it'd be a great feature if you created and exposed the cloudflared/stubby metrics so I could have prometheus scrape them

**Comment by qdm12** [comment]
I'm in the process of rewriting a dns over https client and dns caching server to replace Unbound. Luckily for you, I just got my hands into Prometheus this weekend so I'll add it to the code for sure. It might take a few days though.

On the other hand, for now there is no stubby here, only Unbound glued up with Go.

**Comment by Kampe** [comment]
excellent! thank you! 

oops, got stubby/unbound confused forgot which one you have in this container

**Comment by qdm12** [comment]
Sorry for the loooo00nnng delay, I'm finally about to be done with a DoH + DoT server in Go https://github.com/qdm12/dns/pull/58 I'll add Prom metrics for sure 👍  This is going to be fun!

**Comment by Kampe** [comment]
Love it!  Still running solid! Thanks for your work!

**Comment by qdm12** [comment]
It took a few months, but this is almost done, see https://github.com/qdm12/dns/pull/85 ! 👍

Here are some screenshots of the beta dashboard (I'll share soon the JSON for it as well):

![image](https://user-images.githubusercontent.com/15654980/131743358-d0b3e643-7868-4498-8906-3c3b6eb1f848.png)

![image](https://user-images.githubusercontent.com/15654980/131743497-57a4dc48-b15d-42cc-a0fc-311fff07f2a2.png)

I'll post here when this merges and let you know how to set it up 🎉  (using the `qmcgaw/dns:v2.0.0-beta` image)

**Comment by qdm12** [comment]
Done, you can have metrics with the v2.0.0-beta image and following [this document](https://github.com/qdm12/dns/tree/v2.0.0-beta/readme/metrics#metrics)
