### ISSUE TITLE
unbound refuse all queries from clients

### ISSUE THREAD

**Issue by Nurtalf** [qdm12/dns#50]
`2021-01-02T18:02:10.352Z        INFO    unbound: [1609610530] unbound[20:0] debug: refused query from ip4 192.168.111.10 port 55901 (len 16)
2021-01-02T18:02:10.353Z        INFO    unbound: [1609610530] unbound[20:0] debug: refuse[76:0] 1345010000010000000000000D3139322D3136382D312D31343820363636346532653264363839343034646262663736366263623263633564663204706C6578066469726563740000010001
`
I rolled back to a docker image from 4 days ago and its working.

**Comment by qdm12** [comment]
Thanks for reporting! Indeed there is a major issue 😅 I'll patch all this. In the meantime (for others encountering the bug), use

```
qmcgaw/cloudflare-dns-server:v1.0.0
```

**Comment by qdm12** [comment]
Hello guys, images are now fixed.

- You can use one of the Docker images mentioned in the [readme](https://github.com/qdm12/dns#docker-tags-)
- I removed v1.1.0 and v1.2.0 as they're broken, you can use `v1.1.1` and `v1.2.1` instead.
- `:latest` is fixed too for both image names

🐎 For speedy readers, `:latest` is built, but `v1.1.1` and `v1.2.1` are still building [here](https://github.com/qdm12/dns/actions/runs/458117364) and [here](https://github.com/qdm12/dns/actions/runs/458118662) so please give it a few minutes 😉 

Thanks for your patience!

**Comment by Nurtalf** [comment]
Many thanks! :)
