### ISSUE TITLE
Whitelist for ads?

### ISSUE THREAD

**Issue by woncheol-kim** [qdm12/dns#52]
Hi. I'm wondering if unlocking a domain also unlocks ads, or if there is any option to enlist whitelist for ads.

The domain that matters is investing.com which refuses to show the page normally without accepting ads or pay for premium account. 

At first I thought there must be yet another domain for ads to unlock, but the reply from a guy at the company suggests, while he does not seem know what is DNS, that there's no other domain for ads.

Best,
WonCheol

**Comment by qdm12** [comment]
No unfortunately it just knows about DNS resolution. It not integrated with your browser so won't allow domains depending on the webpage you're visiting.

If you unblock all ads, is the webpage working?

You can try opening the browser console to know what ad domain is blocked and you can add the domains/subdomains to the UNBLOCK environment variable. Then they'll be unblocked for all at all time unfortunately.

Maybe try a browser extension instead and leave ads unblocked in this situation? 🤔

Let me know if you're lost, I can have a look myself 😉

**Comment by woncheol-kim** [comment]
Just editing hosts file solved the issue. :)

**Comment by qdm12** [comment]
Forgive my ignorance, but how? 😄

**Comment by woncheol-kim** [comment]
Sorry. It turned out to be my misunderstanding. I had temporarily changed the DNS to 1.1.1.1 and perhaps the cache remained after I returned the setting back to your docker DNS. And for now I've decided to live with the inconvenience.
