### ISSUE TITLE
Ability to specifiy filters for cloudflare / cleanbrowsing

### ISSUE THREAD

**Issue by barbz127** [qdm12/dns#53]
Hi,

Im looking for a way to specify which IP's are used for cloudflare and cleanbrowsing to enable other functions such as adult filters.

Cloudflare
**Standard 1.1.1.1 / 1.0.0.1 This is the default selected**
Malware-blocking  1.1.1.2 / 1.0.0.2
Malware and adult content-blocking 1.1.1.3 / 1.0.0.3

Cleanbrowsing
**Security Filter 185.228.168.9:   Malicious domains blocked (phishing, malware). - This is the default selected**
Adult Filter      185.228.168.10:  Adult domains blocked; Search Engines set to safe mode; +Security Filter
Family Filter    185.228.168.168: Proxies, VPNs & Mixed Adult Content blocked; Youtube to safe mode; +Adult Filter

Thankyou

**Comment by qdm12** [comment]
Ah interesting I wasn't aware of these. I'll add them tomorrow, assuming they each support DNS over TLS (Cloudflare ones probably do I'd guess).

**Comment by barbz127** [comment]
Thankyou - I only stumbled across them today

**Comment by barbz127** [comment]
https://community.cloudflare.com/t/1-1-1-3-does-not-filter-content-if-queries-are-made-via-dot-dns-over-tls/167730/33

Confirming this is available/working with cloudflare as of a couple of weeks ago

**Comment by qdm12** [comment]
Done (sorry for the delay) 👍  Just a tiny note, `cleanbrowsing` is actually already the security variant. Now you have cleanbrowsing.family, cleanbrowsing.adult, cloudflare.security and cloudflare.family. Cheers!

**Comment by barbz127** [comment]
Thankyou
