### ISSUE TITLE
conflicts with dnsmasq in Manjaro Linux

### ISSUE THREAD

**Issue by woncheol-kim** [qdm12/dns#57]
Hi. I've started to use Manjaro Linux recently. At first, the docker container just worked fine. 

But when I have set up the wifi adapter as hotspot, the docker container exited immediately and I came to know dnsmasq is using the port 53. When I killed the process of dnsmasq, the wifi hotspot did not reach the internet.

What I have already tried:

* edit the port in /etc/dnsmasq.conf
* edit the port in /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
* set dns=none/default/dnsmasq in /etc/NetworkManager/conf.d/dns.conf
* set dns=none/default/dnsmasq in /etc/NetworkManager/NetworkManager.conf
* set dns=none/default/dnsmasq in /etc/NetworkManager/system-connections/*.nmconnection

I've read about NetworkManager in Arch Wiki but could not find the solution.
Do you have any idea to solve the issue?

**Comment by qdm12** [comment]
Personally I encountered the same problem and instantly removed dnsmasq 😄

Maybe you can modify dnsmasq to listen somewhere else, see [this](https://askubuntu.com/a/279539). Let me know how you solve it, I'll add that to the readme.

**Comment by woncheol-kim** [comment]
I've eventually ended up running the docker container with a port other than 53, like 531:53. Surprisingly, it works at least on local machine including wifi hotspot. One remaining issue is that the docker container works only for local machine and I can not get domain names from other devices in local network.

**Comment by qdm12** [comment]
Nice. let's close the issue then.

> One remaining issue is that the docker container works only for local machine and I can not get domain names from other devices in local network.

Please copy pasta this in a new issue. This is a current limitation as it forwards your queries to a DNS provider over TLS. But there is hope for it soon as I'm writing my own dns over tls/https and it's almost done, see #58

Please do not reply here thanks!
