### ISSUE TITLE
v2 program

### ISSUE THREAD

**Issue by qdm12** [qdm12/dns#64]
- [x] Blocked by #58 
- [x] Remove retrocompatible params
- [x] Clean up unbound related things entirely pkg
- [x] Metrics with Prometheus
- [ ] Log out warnings if an old env variable is used
- [ ] DNSSEC
- [ ] Custom redirection hostname -> IP
- [x] Split up OS related dns functions in pkg (e.g. for gluetun)
- [ ] Update readme:
    - [x] with new variables
    - [x] old version and new version, with differences
    - [x] new version tickboxes progression
    - [x] new providers
    - [ ] difference dot vs doh
    - [ ] how each dot and doh work and differ
    - [ ] Move connecting LAN devices etc. in another document

**Comment by JayNewstrom** [comment]
One feature I use in unbound is remapping dns entries to their internal IPs.

```
local-zone: "myserver.mydomain.com" redirect
local-data: "myserver.mydomain.com A 192.168.1.112" 
```

Will something like this be possible in v2?

Happy to help test things if you'd like :)

**Comment by qdm12** [comment]
Yes I can add it for sure, feel free (or others) to comment if you feel like you need a feature that was in Unbound that will disappear.

**Comment by qdm12** [comment]
@JayNewstrom would it be alright to have it as an env variable `DNS_REDIRECT_A=myserver.mydomain.com>(192.168.1.112,192.168.1.113),myserver2.mydomain.com>(192.168.1.114)` for example? I'd like to avoid files to avoid having to set permissions and all as the user should run without root permissions.

**Comment by JayNewstrom** [comment]
That format works for me. But I'm not aware of any standards or anything here.

**Comment by qdm12** [comment]
Closing this as it's not really an issue and `v2.0.0-beta` is about to be finished and merged in the coming days.

@JayNewstrom please see/subscribe to #87 if you have any comments on redirections 😉 Thanks!

Other issues tracking the `v2.0.0-beta` completion have the `v2.0.0` milestone attached.
