### ISSUE TITLE
Oddities with 1.5.0

### ISSUE THREAD

**Issue by qdm12** [qdm12/dns#68]
Reported by @stumpylog in #67 

**Original message start**

I'm also noticing some oddities with 1.5.0.  My container  is listening on port 5053.

```
dig @127.0.0.1 -p 5053 archive.ubuntu.com

; <<>> DiG 9.16.1-Ubuntu <<>> @127.0.0.1 -p 5053 archive.ubuntu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3820
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;archive.ubuntu.com.            IN      A

;; Query time: 63 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Apr 05 15:58:16 PDT 2021
;; MSG SIZE  rcvd: 47
```

vs

```
dig @1.1.1.1 archive.ubuntu.com

; <<>> DiG 9.16.1-Ubuntu <<>> @1.1.1.1 archive.ubuntu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24182
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;archive.ubuntu.com.            IN      A

;; ANSWER SECTION:
archive.ubuntu.com.     50      IN      A       91.189.88.142
archive.ubuntu.com.     50      IN      A       91.189.88.152

;; Query time: 23 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Apr 05 15:58:48 PDT 2021
;; MSG SIZE  rcvd: 79
```

I saw nothing change in the logs when I queried.  I'm going to play around with more verbosity and see what shakes up.

Logging here: https://gist.github.com/stumpylog/42bb37076411dc880916d344e9cb917b

Not the expert, but I see a lot of `nodata`, maybe that's something?

I took the container out of the DNS link, so I could control queries a bit more (and access the internet).  The gist is updated.  Some queries seemed to work, others seems not to.  I just tried some random, popular domains that I figured would be unlikely to currently be broken.

<details>
  <summary>Selected queries</summary>

```
dig @127.0.0.1 -p 5053 cnn.com

; <<>> DiG 9.16.1-Ubuntu <<>> @127.0.0.1 -p 5053 cnn.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19831
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cnn.com.                       IN      A

;; Query time: 127 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Apr 05 16:22:55 PDT 2021
;; MSG SIZE  rcvd: 36
```
```
dig @127.0.0.1 -p 5053 cnn.com

; <<>> DiG 9.16.1-Ubuntu <<>> @127.0.0.1 -p 5053 cnn.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19831
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cnn.com.                       IN      A

;; Query time: 127 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Apr 05 16:22:55 PDT 2021
;; MSG SIZE  rcvd: 36
```
```
dig @127.0.0.1 -p 5053 github.com

; <<>> DiG 9.16.1-Ubuntu <<>> @127.0.0.1 -p 5053 github.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38513
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             3571    IN      A       192.30.255.113

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Apr 05 16:22:49 PDT 2021
;; MSG SIZE  rcvd: 55
```

```
dig @127.0.0.1 -p 5053 amazon.com

; <<>> DiG 9.16.1-Ubuntu <<>> @127.0.0.1 -p 5053 amazon.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42578
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;amazon.com.                    IN      A

;; ANSWER SECTION:
amazon.com.             3600    IN      A       205.251.242.103
amazon.com.             3600    IN      A       54.239.28.85
amazon.com.             3600    IN      A       176.32.103.205

;; Query time: 127 msec
;; SERVER: 127.0.0.1#5053(127.0.0.1)
;; WHEN: Mon Apr 05 16:23:01 PDT 2021
;; MSG SIZE  rcvd: 87
```
</details>

**Original message end**

**Comment by qdm12** [comment]
It seems there is no difference between 1.2.1 and 1.5.0 Unbound wise, I checked its version is also the same `1.10.1` and Alpine stayed at `3.12` for now. Maybe these are external issues? Did you try changing DoT provider? Does it behave differently compared to previous versions? Note that Unbound does a bunch of things versus a standard OS resolver so that might explain the difference.

**Comment by stumpylog** [comment]
I should have mentioned, I updated the container from 1.4.0 to 1.5.0.  With 1.4.0, the DNS has been solid.  I haven't ever noticed anything like this in normal usage.  If I revert back to that image, I'm not able to reproduce.

I changed the DoT provider from cloudflare to google (running 1.5.0).  I still see no IP in the dig response for some big domains, like reddit.com and microsoft.com.  I've been waiting until the health checks healthy before running my queries.

**Comment by qdm12** [comment]
Ah yes I see it now as well. Although the super strange thing is that it fails but not always. No idea why though, I doubt it has to do with my code as this seems more like an Unbound issue. 😢 Although its version didn't change either, very strange indeed. I'll let you know if I find anything.

**Comment by qdm12** [comment]
@stumpylog actually you were 100% right, my bad! This behavior causes the issue #67 as the program is designed to crash if the initial resolution doesn't work. I closed #67 in favor of this one. I'll dig into what's up, but it really seems Unbound related to me.

I fixed a [program](https://github.com/qdm12/updated) I have running every 24 hours to update https://github.com/qdm12/files from which DNSSEC files are taken from at container boot; They changed the root anchors where the checksum changed and I got lazy the last few days fixing the checksum env variable.... That might had solved it 🤔 Try rebooting v1.5.0 so it re-downloads that root anchors file.

Also FYI that root anchor file is written in the Docker image but is fetched from qdm12/files to get an updated version if, say, you run v1.2.1 which has an outdated root anchor. My guess would be that the Unbound program has the same version but more recent ones might not like outdated crypto files whilst old ones are okay with it?

Let's see if that fixes it. If it does, I'll set up some code to directly fetch and parse the root anchors from this program instead of going through hoops and depending on my program running in my closet behind me 😄

**Comment by stumpylog** [comment]
Hm, I think it would have the updated root anchors. I've been re/creating the container enough I would think it would have grabbed the latest files. I'll play around with it as I can tomorrow. 

Honestly, looking forward to the v2 without Unbound to add confusion.

**Comment by qdm12** [comment]
Ooops found the bug (by working on v2...), I believe there are two Unbound running at the same time and they conflict each other.

I'm working on a fix although it's not so trivial to fix... So my spaghetti code was at fault in the end!

**Comment by qdm12** [comment]
Alright finally!

Made image tags for `:v1.4.1` and `v1.5.1`; `:latest` should also be fixed now. It's a bug I introduced in v1.4.0 where the 'loop' handling the lifecycle of Unbound was all messed up, sometimes not shutting down the previous instance and somehow they would coexist.

And on top of that (that drove me nuts), v1.5.0 parses IP subnets (instead of just throwing them to Unbound as dumb strings) and that caused the private address `::ffff:0:0/96` to be interpreted as `0.0.0.0/0` which means block everything... That really drove me nuts for hours! But anyway, it's now removed, it looks like it's all good now.

I'm 95% done for the V2 as well, but I'm happy i fixed the Unbound version. The only problem with that v2 is that it doesn't support DNSSEC validation yet, but I guess we can have a beta version without for now.

**Comment by qdm12** [comment]
One last thing, I have an image `:v2.0.0-beta` with documentation [here](https://github.com/qdm12/dns/tree/v2.0.0-beta#environment-variables) have a go if you want. It's full Go and supports DoT as well as DoH. Ideally I want as mentioned above to add DNSSEC before jumping there, but it's still pretty much functional still.

**Comment by rtmgllc** [comment]
Works! Thanks again!
