### ISSUE TITLE
Early exit missed?

### ISSUE THREAD

**Issue by mm97mm** [qdm12/dns#69]
Isn't early exit missed here? As well as below, where we refuse query to a blacklisted domain but we still go, resolve and respond with ip later?

https://github.com/qdm12/dns/blob/4321cd7d2b8f463eee1ee9c296d4d824c78cffc7/pkg/dot/handler.go#L37
https://github.com/qdm12/dns/blob/4321cd7d2b8f463eee1ee9c296d4d824c78cffc7/pkg/dot/handler.go#L46
https://github.com/qdm12/dns/blob/4321cd7d2b8f463eee1ee9c296d4d824c78cffc7/pkg/dot/handler.go#L61

**Comment by qdm12** [comment]
Thank you a hundred times. How did I not see that. Plus I made the copy pasta mistake on both dot and doh 🤮

It's now fixed on the branch/image tag v2.0.0-beta, I will fix it on master and v1.x.x branches later.
