### ISSUE TITLE
Hardcoded port in log message

### ISSUE THREAD

**Issue by mm97mm** [qdm12/dns#72]
https://github.com/qdm12/dns/blob/4321cd7d2b8f463eee1ee9c296d4d824c78cffc7/pkg/dot/server.go#L48
Also, shouldn't `853` be default for DoT? 
I came only with `s.dnsServer.Addr` here

**Comment by qdm12** [comment]
No it's actually not a DoT server, it's a dumb DNS server which forwards the messages to DoT/DoH servers so more of a DNS server+DoT/DoH client really. Thanks for the PR as well 👍

**Comment by qdm12** [comment]
Closed by 7569778312c5639fde7b7b789280703ba3d62122 and 8870bf536a1f6f6fd599ec6f03f7398046ef7ff3
