### ISSUE TITLE
dns resolve error

### ISSUE THREAD

**Issue by n3t5ky** [qdm12/dns#8]
I had problem today with resolving "ads.google.com". 

I figured it out, that --env BLOCK_MALICIOUS=off  solve this.

**Comment by qdm12** [comment]
It's because `BLOCK_MALICIOUS` also blocks ads related domain names. I might remove it from the ban list for the next update. Thanks for posting!

**Comment by qdm12** [comment]
@ex0nuss sorry that took longer than expected.

I removed the [tracking-nl.txt](https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt) list from the malicious list of urls in https://github.com/qdm12/updated/commit/123a57ffd8a78c7ceebd72feda19ddd44fe9a799 that might solve it. You can try by restarting the container or wait for it to update itself. Thanks for your patience!
