### ISSUE TITLE
Use only DOT or only DOH in v2.0.0-beta

### ISSUE THREAD

**Issue by faffymcfafferson** [qdm12/dns#84]
Hi, is it possible to only use one method of dns resolution.

say I only want to use DOH, but tomorrow change to just DOT. 

"Split-horizon DNS (randomly picks one of the DoT/DoH providers specified for each request)"

Thanks!

**Comment by qdm12** [comment]
Sorry I need to update the readme for v2.0.0-beta. See [here in the Dockerfile](https://github.com/qdm12/dns/blob/v2.0.0-beta/Dockerfile#L66) for a list of environment variables (this may change without notice).

By default it's all DoT. You need to set `UPSTREAM_TYPE=DoH` to use it over https.

Note that DoH requires some form of DoT from time to time to resolve the DoH endpoint (e.g. `one.one.one.one` to an IP address). I would think most implementations out there use plaintext DNS to resolve DoH endpoints, which sort of defeats the purpose of DoH (although it does https so there are tls certificates to prevent spoofing still) 😄

**Comment by qdm12** [comment]
Fixed v2.0.0-beta documentation in e78fe0aa16a93aefe0d2877fa77da0bd944242ef
